services:
  - type: web
    name: rag-chatbot
    env: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn app:app --timeout 120"
    envVars:
      - key: HF_TOKEN
        sync: false