services:
  - type: web
    name: rag-chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python indexer.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: HF_TOKEN
        sync: false