services:
  - type: web
    name: rag-chatbot
    env: python
    plan: free
    buildCommand: "fallocate -l 1G /swapfile && mkswap /swapfile && swapon /swapfile && pip install -r requirements.txt && python indexer.py"
    startCommand: "gunicorn app:app --timeout 120"
    envVars:
      - key: HF_TOKEN
        sync: false